stages:
    - test
    - deploy
# Test in a CPU, only 1 epoch
test:
    stage: test
    image: tensorflow/tensorflow:1.10.0-py3
    script:
        - python code-to-run.py 1
# Deploy in a GPU and run all epochs
deploy:
    image: google/cloud-sdk
    stage: deploy
    script:
        # Install kubectl from https://gitlab.com/gitlab-examples/kubernetes-deploy
        - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/latest.txt)/bin/linux/amd64/kubectl && chmod +x /usr/bin/kubectl
        - kubectl version --client
        # Authorization in gcloud see https://medium.com/@gaforres/publishing-google-cloud-container-registry-images-from-gitlab-ci-23c45356ff0e
        - echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
        - gcloud auth activate-service-account --key-file gcloud-service-key.json || true    
        # In case the cluster was already initiated, it should be deleted
        - gcloud --quiet container clusters delete  ${GCLOUD_CLUSTER_NAME} --zone ${GCLOUD_ZONE} --project ${GCLOUD_PROJECT} || true
        # Create a cluster on Google Cloud with a GPU 
        - |
          gcloud container clusters create ${GCLOUD_CLUSTER_NAME} \
            --project ${GCLOUD_PROJECT} \
            --machine-type "n1-highmem-2" \
            --accelerator "type=nvidia-tesla-v100,count=1" \
            --image-type "UBUNTU" \
            --num-nodes "1" \
            --zone ${GCLOUD_ZONE} 
        - gcloud container clusters get-credentials ${GCLOUD_CLUSTER_NAME} --zone ${GCLOUD_ZONE} --project ${GCLOUD_PROJECT}          
        - kubectl cluster-info || true
        # Secrets
        - kubectl create secret docker-registry regsecret --docker-server="nvcr.io" --docker-username='$oauthtoken' --docker-password=${DOCKER_REGISTRY_PASSWORD} --docker-email="email@email.com" --namespace=default || true
        # Code as configmap
        - kubectl create configmap code-to-run --from-file=code-to-run.py --namespace=default
        # Install drivers in all the nodes with Nvidia GPUs
        - kubectl apply -f daemonset.yaml --namespace=kube-system # https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/ubuntu/daemonset.yaml 
        # Run the code as a job
        - kubectl create -f gke-gpu-gitlab-job.yaml --namespace=default
        # Wait until the code is finished
        - until kubectl get jobs my-gpu-job --namespace=default -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep True ; do sleep 5 ; echo "job in progress"; done;
        # Get results
        - kubectl logs $(kubectl get pods --selector=job-name=my-gpu-job --output=jsonpath={.items..metadata.name} --namespace=default) --namespace=default
        # Shut down the gcloud cluster
        - gcloud --quiet container clusters delete  ${GCLOUD_CLUSTER_NAME} --zone ${GCLOUD_ZONE} --project ${GCLOUD_PROJECT} || true